### ISSUE TITLE
[AVM Module Issue]: add cluster controlplane identity to outputs

### ISSUE THREAD

**Issue by hangerma-jambit** [Azure/terraform-azurerm-avm-res-containerservice-managedcluster#90]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Currently, the module outputs only feature the id of the kubelet identity ("kubelet_identity"). 

**Please also include the id of the control plane identity in the outputs** `azurerm_kubernetes_cluster.this.identity[0].principal_id`.

Use case: 
To control ingress via k8s service ("LoadBalancer" type) i need to grant the controlplane access to specific public ips. This could be accomplished with the `avm-res-authorization-roleassignment` module without the need to create a new module if this output was added. 

Alternative solution:
This use case could also be addressed by including the option to add role assignments to the controlplane identity. If the latter is the preferred option please also include the possibility to add role assignments to the kubelet identity. This is something other aks module already provide https://github.com/Azure/terraform-azurerm-aks/blob/9b3948525970cb893aefc992ee7dba5604b9cdc2/role_assignments.tf#L1-L8 

I am aware of the statement in https://github.com/Azure/terraform-azurerm-avm-res-containerservice-managedcluster/issues/15 but for me this is not ideal as a cluster is usually created after the container registry and going back and forth applying modules when creating new clusters is not ideal.

**Comment by kostyazgara** [comment]
This issue was closed as fixed in 0.4.0, but the fix is incomplete. The `identity_principal_id` output still always returns null as of v0.4.3.

The output declaration exists, but "identity" was never added to response_export_values on the azapi_resource in https://github.com/Azure/terraform-azurerm-avm-res-containerservice-managedcluster/blob/81aa121a9fd534ad295ce4af1991b469f81ccb3e/main.tf#L15-L27. Without it, azapi_resource.this.output.identity.principalId is always undefined and try() falls back to null.

The same applies to `identity_tenant_id`.

The fix should be adding "identity" to the response_export_values list:

```
response_export_values = [
    "identity",  # <-- missing
    "properties.addonProfiles.azureKeyvaultSecretsProvider",
    ...
]
```

Could this issue be reopened?

**Comment by blagovestkarakashev** [comment]
@matt-FFFFFF please see comment above, issue still happening.

**Comment by matt-FFFFFF** [comment]
Apologies, on this now
